site_name: Disc ID
site_url: https://discid.org
theme:
  name: material
  palette:
    - scheme: light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.share
    - search.suggest
    - toc.integrate
  icon:
    repo: 'fontawesome/brands/github'
  logo: 'images/Disc_ID_Square.png'
  favicon: 'images/favicon.png'
repo_name: Disc-ID/discid.org
repo_url: 'https://github.com/Disc-ID/discid.org'
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - blog:
      blog_dir: project-updates
      blog_toc: true
      post_excerpt: required
  - rss:
      match_path: project-updates/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - social:
      cards_layout_options:
        background_color: "#343d46"
edit_uri: 'edit/main/docs/'
nav:
  - Home: index.md
  - Project Updates: project-updates/index.md
  - Specifications:
      - Disc ID Specification: specifications/disc-id.md
      - Data Maps: specifications/data-maps.md
      - NDEF: specifications/ndef.md
  - Implementations: implementations.md
  - Guides & Reference: guides-reference.md
  - About: about.md
extra:
  social:
  - icon: 'fontawesome/brands/github'
    link: 'https://github.com/Disc-ID/discid.org'
extra_css:
  - 'stylesheets/extras.css'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - meta
  - pymdownx.snippets:
      check_paths: true
      base_path: 'docs/snippets'
  - tables
  - toc:
      permalink: true
      toc_depth: 4